@startuml

class Video {
    - id: Long
    - title: String
    - description: String
    - path: String
    - duration: long
    - views: long
    - createdAt: LocalDate
    - updatedAt: LocalDate
}

class VideoResource {
    - id: Long
    - path: String
    - processingTime: long
}

enum Resolution {
    + HD
    + SD
}

Video "1" *-right-> "*" VideoResource
VideoResource "*" o-right-> "1" Resolution

@enduml