@startuml
class User {
    - id: Long
    - name: String
    - email: String
    - password: String
}

class Course {
    - id: Long
    - title: String
    - description: String
}

class Module {
    - id: Long
    - title: String
    - description: String
}

class Video {}

User "1" o-> "*" Course
Course "1" *-> "*" Module
Module "1" *-> "*" Video


@enduml